### PR TITLE
Handle multi-lingual private files.

### PR DESCRIPTION
**Pull request by slashrsm**
Related to https://github.com/nginxinc/nginx-wiki/pull/314

### CODE REVIEW

**Review by zaporylie — COMMENTED** [review]
Based on https://api.drupal.org/api/drupal/includes%21iso.inc/function/_locale_get_predefined_list/7.x it would not work for some languages (like British English or Swiss German). Agree?

**Comment by slashrsm** [comment]
Good point. Fixed.

**Comment by slashrsm** [comment]
Also fixed upstream.

**Review by zaporylie — APPROVED** [review]
Upstream merged, lets merge this one as well.

**Pull request merged**
